<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>LodClient</RootNamespace>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);android/**;build/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
